-- ==========================================
-- AURUM ESTATES - SUPABASE DATABASE SCHEMA
-- Save this in the Supabase SQL Editor & Run
-- ==========================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE,
    category TEXT,
    status TEXT CHECK (status IN ('ongoing', 'completed', 'upcoming')) DEFAULT 'ongoing',
    location TEXT,
    city TEXT,
    price TEXT, -- Maps to admin panel's general form price field
    price_min NUMERIC,
    price_max NUMERIC,
    price_label TEXT,
    area_min INTEGER,
    area_max INTEGER,
    area_label TEXT,
    thumbnail TEXT,
    images TEXT[] DEFAULT '{}',
    is_featured BOOLEAN DEFAULT FALSE,
    amenities TEXT[] DEFAULT '{}',
    highlights TEXT[] DEFAULT '{}',
    short_description TEXT,
    description TEXT,
    rera_number TEXT,
    floor_plans JSONB DEFAULT '[]'::jsonb,
    meta_title TEXT,
    meta_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. INQUIRIES TABLE
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT NOT NULL,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    message TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. AUTOMATIC SLUGIFY TRIGGER (PL/pgSQL)
-- This automatically slugifies titles upon insertion if slug is not provided.
CREATE OR REPLACE FUNCTION slugify(title TEXT) 
RETURNS TEXT AS $$
DECLARE
    slug TEXT;
BEGIN
    -- Lowercase the title, replace non-alphanumeric chars with hyphens, and clean up ends
    slug := lower(regexp_replace(title, '[^a-zA-Z0-9]+', '-', 'g'));
    slug := regexp_replace(slug, '^-|-$', '', 'g');
    RETURN slug;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_project_slug() 
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.slug IS NULL OR NEW.slug = '' THEN
        NEW.slug := slugify(NEW.title);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Bind the slugify trigger to projects table
DROP TRIGGER IF EXISTS trigger_set_project_slug ON public.projects;
CREATE TRIGGER trigger_set_project_slug
BEFORE INSERT OR UPDATE ON public.projects
FOR EACH ROW
EXECUTE FUNCTION set_project_slug();

-- 5. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- 6. PROJECTS RLS POLICIES
-- A. Select policy: Anyone can read projects
DROP POLICY IF EXISTS "Allow public read access on projects" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated admins all access on projects" ON public.projects;
DROP POLICY IF EXISTS "Allow public all access on projects" ON public.projects;

CREATE POLICY "Allow public all access on projects" 
ON public.projects FOR ALL 
USING (true)
WITH CHECK (true);

-- 7. INQUIRIES RLS POLICIES
-- A. Insert/All policy: Allow full operations via public anon key
DROP POLICY IF EXISTS "Allow public insert on inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Allow authenticated admins all access on inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Allow public all access on inquiries" ON public.inquiries;

CREATE POLICY "Allow public all access on inquiries" 
ON public.inquiries FOR ALL 
USING (true)
WITH CHECK (true);

-- 8. STORAGE BUCKET CONFIGURATION FOR IMAGES
-- Run these inserts to register the public 'project-images' bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 9. STORAGE RLS POLICIES
-- A. Select policy: Anyone can view images from 'project-images' bucket
DROP POLICY IF EXISTS "Allow public read on project-images bucket" ON storage.objects;
CREATE POLICY "Allow public read on project-images bucket"
ON storage.objects FOR SELECT
USING (bucket_id = 'project-images');

-- B. Insert policy: Allow public uploads (anon key uploads from backend) into 'project-images' bucket
DROP POLICY IF EXISTS "Allow authenticated insert on project-images bucket" ON storage.objects;
DROP POLICY IF EXISTS "Allow public insert on project-images bucket" ON storage.objects;
CREATE POLICY "Allow public insert on project-images bucket"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'project-images');

-- C. Delete policy: Allow public deletions (anon key deletions from backend) from 'project-images' bucket
DROP POLICY IF EXISTS "Allow authenticated delete on project-images bucket" ON storage.objects;
DROP POLICY IF EXISTS "Allow public delete on project-images bucket" ON storage.objects;
CREATE POLICY "Allow public delete on project-images bucket"
ON storage.objects FOR DELETE
USING (bucket_id = 'project-images');
